#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
  path: /
  controller: App\Controller\HomeController::index

property.index:
  path: /biens
  controller: App\Controller\PropertyController::index

property.show:
  path: /bien/{id}/{slug}
  controller: App\Controller\PropertyController::showProperty

admin.property.show:
  path: /admin/property
  controller: App\Controller\Admin\AdminPropertyController::index

admin.property.edit:
  path: /admin/property/edit/{id}/{slug}
  controller: App\Controller\Admin\AdminPropertyController::edit

admin.property.create:
  path: /admin/property/new
  controller: App\Controller\Admin\AdminPropertyController::create